ベースディレクトリと、出力ディレクトリを設定します。

In [1]:
############################################
BaseDir   = 'IntroDDSJpn/Chap00/'
OutputDir = '0Python-NumPy/'

Google Colabかどうかを判別し、このJupyter Notebookのあるディレクトリを特定します。

In [ ]:
############################################
import sys
import os
############################################
def IsGoogleColab():
  if 'google.colab' in sys.modules:
    return True
  else:
    return False
############################################
if IsGoogleColab():
  #
  from google.colab import drive
  drive.mount('/content/drive')
  #
  IpynbDir = 'drive/My Drive/Colab Notebooks/' + BaseDir
else:
  #
  IpynbDir =  os.getcwd() + '/'
############################################
print( 'ipynb file path = %s' % IpynbDir )

ipynb file path = d:\home\iakai\CY\Docs\Kuma3Curriculum\2025森北出版\GitHubIntroDDSJpn\IntroDDSJpn\Chap00


Pythonで数値計算や配列を効率的に行うためのパッケージ
* https://numpy.org/
* NumPy Reference: https://numpy.org/doc/stable/reference/index.html

In [3]:
############################################
import numpy as np
print('numpy      Ver.', np.__version__)
############################################
# 1 次元配列
a = np.array([1, 2, 3])
b = np.array([2, 2, 0])
# 2 次元配列
bb = np.array([[1, 2, 3], [4, 5, 6]])
# 3 次元配列
ddd = np.array([ [ [1,  2, 3],
                   [4,  5, 6],
                   [7,  8, 9],
                   [10,11,12] ],
                 [ [13,14,15],
                   [16,17,18],
                   [19,20,21],
                   [22,23,24] ] ] )

numpy      Ver. 1.26.4


ベクトル・行列演算
* $\boldsymbol{a}=(a_{1},\cdots,a_{i},\cdots,a_{n})$, $\boldsymbol{b}=(b_{1},\cdots,b_{i},\cdots,b_{n})$

* アダマール(Hadamard)積:
  $$
  (a_{1}b_{1},\cdots,a_{i}b_{i},\cdots,a_{n}b_{n})
  $$

* 内積:  
  $$
  \boldsymbol{a}\cdot\boldsymbol{b}
  =
  \sum_{i=1}^{n}a_{i}b_{i}
  $$

* 外積($n=3$の場合):  
  $$\boldsymbol{a}\times\boldsymbol{b}
  =
  \left|
  \begin{array}{ccc}
    \boldsymbol{e}_{x}&\boldsymbol{e}_{y}&\boldsymbol{e}_{z} \\
    a_{x} & a_{y} & a_{z} \\
    b_{x} & b_{y} & b_{z}
  \end{array}
  \right|
  $$

* 直積($n=3$の場合)
  $$
  \boldsymbol{a}\otimes\boldsymbol{b}
  =
  \boldsymbol{a}\boldsymbol{b}^{T}
  =
  \left(
    \begin{array}{c}
      a_{1}\\
      a_{2}\\
      a_{3}
    \end{array}
  \right)
  \left(
    \begin{array}{ccc}
      b_{1} & b_{2} & b_{3}
    \end{array}
  \right)
  $$

* 行列積
  $$
  \left(
    \begin{array}{ccc}
      c_{11} & \cdots & c_{1n} \\
      \vdots & \ddots & \vdots \\
      c_{11} & \cdots & c_{1n}
    \end{array}
  \right)
  \left(
    \begin{array}{c}
      d_{1} \\
      \vdots \\
      d_{n}
    \end{array}
  \right),
  \left(
    \begin{array}{ccc}
      d_{1} & \cdots d_{n}
    \end{array}
  \right)
  \left(
    \begin{array}{ccc}
      c_{11} & \cdots & c_{1n} \\
      \vdots & \ddots & \vdots \\
      c_{11} & \cdots & c_{1n}
    \end{array}
  \right)$$

In [4]:
############################################
print( 'a=', a, ', b=', b )
# アダマール(Hadamard)積
print( 'a*b=', a*b )
# 内積
print( 'a@b=', a@b )
print( 'np.dot( a, b )=', np.dot( a, b ) )
# 外積
print( 'np.cross( a, b )=', np.cross( a, b ) )
# 直積
c = np.outer( a, b )
print( 'np.outer( a, b )=', np.outer( a, b ) )
############################################
# 行列積
c = np.array( [ [1, 2], [3, 4] ] )
d = np.array( [ [1], [2] ] )
print( c @ d )
print( d.T @ c )

a= [1 2 3] , b= [2 2 0]
a*b= [2 4 0]
a@b= 6
np.dot( a, b )= 6
np.cross( a, b )= [-6  6 -2]
np.outer( a, b )= [[2 2 0]
 [4 4 0]
 [6 6 0]]
[[ 5]
 [11]]
[[ 7 10]]


統計処理
* データ: $\boldsymbol{X}=\{x_1,\cdots,x_n\}$,  荷重: $\boldsymbol{W}=\{w_1,\cdots,w_n\}$

* 最大値、最小値: ${\rm max}(\boldsymbol{X})$,  ${\rm min}(\boldsymbol{X})$,

* 最大値、最小値のインデックス: ${\rm argmax}(\boldsymbol{X})$,  ${\rm argmin}(\boldsymbol{X})$,

* 平均値:
    $$\overline{X}=\frac{1}{n}\sum_{i=1}^{n}x_{i}$$

* 荷重平均値:
    $$\frac{\sum_{i=1}^{n}w_{i}x_{i}}{\sum_{i=1}^{n}w_{i}}$$

* 分散:
    $$\sigma^{2}=\frac{1}{n-{\rm{ddof}}}\sum_{i=1}^{n}\left(x_{i}-\overline{X}\right)^2$$

In [5]:
############################################
Xs = np.random.normal( scale=3.0,size=10 )
print( Xs )
Ws = np.random.gamma( 5.0, size=10 )
print( Ws )
# 最大値、最小値
print( 'amax = ', np.amax(Xs) )
print( 'amin = ', np.amin(Xs) )
# 最大値、最小値のインデックス
print( 'argmax = ', np.argmax(Xs) )
print( 'argmin = ', np.argmin(Xs) )
# 平均値、中央値
print( 'mean    = ', np.mean(Xs) )
print( 'average = ', np.average(Xs,
                     weights=Ws) )
print( 'median  = ', np.median(Xs) )
# 標準偏差、分散
print( 'std = ', np.std(Xs, ddof=1) )
print( 'var = ', np.var(Xs, ddof=1) )

[-0.80060496  2.90939191  0.81468051 -4.49246468  1.29955249 -0.86856057
 -2.89844614  4.29114895 -1.08042396  4.66469303]
[7.2350637  1.75695614 8.20268971 3.71543891 4.72594856 3.3797481
 4.8544861  9.14710077 5.44999891 0.95899704]
amax =  4.6646930254647
amin =  -4.492464675142339
argmax =  9
argmin =  3
mean    =  0.3838966573764601
average =  0.32943235260670906
median  =  0.007037772682603971
std =  2.9937447141074416
var =  8.962507413246247


共分散

$$
s_{xy} = \frac{1}{n - 1} \displaystyle \sum_{i = 1}^n
{(x_i - \overline{x})(y_{i} - \overline{y})},\;\;\;({\rm{}bias=False: default})
$$

$$s_{xy} = \frac{1}{n} \displaystyle \sum_{i = 1}^n
{(x_i - \overline{x})(y_{i} - \overline{y})},\;\;\;({\rm{}bias=True})$$

$$\Sigma
=
\left(
\begin{array}{ccc}
  s_{11} & \cdots & s_{1n} \\
  \vdots & \ddots & \vdots \\
  s_{n1} & \cdots & s_{nn}
\end{array}
\right)
$$

* テストの相関関係
  $$
  \begin{array}{c|cccc}
    & 学生A & 学生B & 学生C & 学生D \\
    \hline
    数学 & 78 & 57 & 37 & 42 \\
    国語 & 46 & 73 & 51 & 80 \\
    物理 & 63 & 44 & 48 & 23
  \end{array}
  $$
  $$
  \begin{array}{c|ccc}
    & 数学 & 国語 & 物理 \\
    \hline
    数学 & 254.25 &  -94.75 &  160.25 \\
    国語 & -94.75 &  205.25 & -181.75 \\
    物理 & 160.25 & -181.75 &  204.25
  \end{array}
  $$

In [6]:
############################################
math = np.array([78,57,37,42])
jpn  = np.array([46,73,51,80])
phys = np.array([63,44,48,23])
# テストの点
test = np.array( [math, jpn, phys] )
# 共分散
print( np.cov( test, bias=True ))

[[ 254.25  -94.75  160.25]
 [ -94.75  205.25 -181.75]
 [ 160.25 -181.75  204.25]]
