ベースディレクトリと、出力ディレクトリを設定します。

In [1]:
############################################
BaseDir   = 'IntroDDSJpn/Chap00/'
OutputDir = '0Python-pandas/'

Google Colabかどうかを判別し、このJupyter Notebookのあるディレクトリを特定します。

In [2]:
############################################
import sys
import os
############################################
def IsGoogleColab():
  if 'google.colab' in sys.modules:
    return True
  else:
    return False
############################################
if IsGoogleColab():
  #
  from google.colab import drive
  drive.mount('/content/drive')
  #
  IpynbDir = 'drive/My Drive/Colab Notebooks/' + BaseDir
else:
  #
  IpynbDir =  os.getcwd() + '/'
############################################
print( 'ipynb file path = %s' % IpynbDir )

ipynb file path = d:\home\iakai\CY\Docs\Kuma3Curriculum\2025森北出版\GitHubIntroDDSJpn\IntroDDSJpn\Chap00/


NumPy: Pythonで数値計算や配列を効率的に行うためのパッケージ
* https://numpy.org/
* NumPy Reference: https://numpy.org/doc/stable/reference/index.html

In [3]:
############################################
import numpy as np
print('numpy      Ver.', np.__version__)
############################################

numpy      Ver. 1.26.4


pandas: Pythonでデータ解析を支援するパッケージ
* https://pandas.pydata.org/
* pnadas User Guide: https://pandas.pydata.org/docs/user_guide/index.html
* Excelファイルからデータをデータフレームに読み込む。

In [4]:
############################################
import pandas as pd
print('pandas     Ver.', pd.__version__)
############################################
# Excelファイルからデータを
# データフレームに読み込む。
#
df_Rdata = pd.read_excel( IpynbDir +
                    'LSQMdata05.xlsx' )

pandas     Ver. 2.2.3


* データフレームの列をNumPyのarrayに変換

In [5]:
############################################
# データフレームの列をNumPyのarrayに変換
x_i      = np.array( df_Rdata['x_length'    ] )
sigma_xi = np.array( df_Rdata['x_sigma'     ] )
print( x_i )
print( sigma_xi )
#
y_i      = np.array( df_Rdata['y_resistance'] )
sigma_yi = np.array( df_Rdata['y_sigma'     ] )
print( y_i )
print( sigma_yi )

[0.0419 0.0628 0.0898 0.1014 0.1429 0.1445 0.1698 0.1841]
[0.0084 0.0094 0.0105 0.0046 0.007  0.0079 0.0112 0.0049]
[0.074 0.105 0.089 0.14  0.16  0.182 0.214 0.234]
[0.067 0.025 0.031 0.047 0.011 0.01  0.011 0.01 ]


* NumPyのarrayからデータフレームを作成

In [6]:
############################################
# NumPyのarrayからデータフレームを作成
df_New = pd.DataFrame( { 'x_i':       x_i,
                         'sigma_xi':  sigma_xi,
                         'y_i':       y_i,
                         'sigma_yi':  sigma_yi } )
df_New

x_i  sigma_xi    y_i  sigma_yi
0  0.0419    0.0084  0.074     0.067
1  0.0628    0.0094  0.105     0.025
2  0.0898    0.0105  0.089     0.031
3  0.1014    0.0046  0.140     0.047
4  0.1429    0.0070  0.160     0.011
5  0.1445    0.0079  0.182     0.010
6  0.1698    0.0112  0.214     0.011
7  0.1841    0.0049  0.234     0.010

出力先のフォルダ(ディレクトリ)を準備

In [7]:
############################################
# 出力先のフォルダ(ディレクトリ)を準備
FilePath = IpynbDir + OutputDir
print( 'FilePath = %s' % FilePath )
#
if( True != os.path.isdir(FilePath) ):
    print('  making %s' % FilePath )
    os.mkdir(FilePath)
else:
    print(' %s is exist.' % FilePath )

FilePath = d:\home\iakai\CY\Docs\Kuma3Curriculum\2025森北出版\GitHubIntroDDSJpn\IntroDDSJpn\Chap00/0Python-pandas/
  making d:\home\iakai\CY\Docs\Kuma3Curriculum\2025森北出版\GitHubIntroDDSJpn\IntroDDSJpn\Chap00/0Python-pandas/


* NumPyのarrayからデータフレームを作成

In [8]:
############################################
# NumPyのarrayからデータフレームを作成
df_New = pd.DataFrame( { 'x_i':       x_i,
                         'sigma_xi':  sigma_xi,
                         'y_i':       y_i,
                         'sigma_yi':  sigma_yi } )
print( df_New )
############################################
# データフレームをxlsxに出力
df_New.to_excel( FilePath + 'Python-pandas-01.xlsx', sheet_name='new_sheet')

      x_i  sigma_xi    y_i  sigma_yi
0  0.0419    0.0084  0.074     0.067
1  0.0628    0.0094  0.105     0.025
2  0.0898    0.0105  0.089     0.031
3  0.1014    0.0046  0.140     0.047
4  0.1429    0.0070  0.160     0.011
5  0.1445    0.0079  0.182     0.010
6  0.1698    0.0112  0.214     0.011
7  0.1841    0.0049  0.234     0.010
